### ISSUE TITLE
Error: [dispatch] [fps-utils] hook: Error: obsolete definition (S_ABNORMALITY_BEGIN.4)

### ISSUE THREAD

**Issue by FrankMora** [Risenio/fps-utils#10]
Error: [dispatch] [fps-utils] hook: Error: obsolete definition (S_ABNORMALITY_BEGIN.4)

**Comment by Risenio** [comment]
Thanks for reporting.

Should be fixed in [c07301c](https://github.com/Risenio/fps-utils/commit/c07301c31c2b556e2224798d0734b4bdc9f5c71a).
