### ISSUE TITLE
hidden players still visible

### ISSUE THREAD

**Issue by lidel97** [Risenio/fps-utils#6]
i have visually blocked players with the comand " fps hide nameplayer", it apparently works but i still see them if i log another character or change channel\ region. the module says " nameplayer already hidden" but the problem persists even if i type - fps show nameplayer- and hide again.

**Comment by Risenio** [comment]
This must have been fixed in [2fe55aa](https://github.com/Risenio/fps-utils/commit/2fe55aaac82d1da608a484cb5a8134842157361d).
If the issue still presets till now, reopen the issue.
