### ISSUE TITLE
hidden players still visible (again)

### ISSUE THREAD

**Issue by lidel97** [Risenio/fps-utils#7]
i copy and paste again the issue:

i have visually blocked players with the comand " fps hide nameplayer", it apparently works but i still see them if i log another character or change channel\ region. the module says " nameplayer already hidden" but the problem persists even if i type - fps show nameplayer- and hide again.

just few minutes ago i had in front of me a player that i hid days ago but it's still visible, the system says infact " already hidden" but it does not work

**Comment by Risenio** [comment]
Fixed in [31653fa](https://github.com/Risenio/fps-utils/commit/31653fa6f28778d158ef3475d940a8ebde899c5b).
Thank you for reporting such issue.
